title: "KKSecOps"
author: "K"
description: "K's Portfolio Blog"
permalink: /:year/:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
paginate: 5
paginate_path: /page/:num/ #test this

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true            # show a sidebar instead of the usual header
show_description: false       # dont include description
show_minimal: false             # remove all clutter
dark_header: true #does this work?

show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "home.html", sidebaricon: home}
  - {file: "projects.html", sidebaricon: code}
  - {file: "writeups.html", sidebaricon: user-secret}
  - {file: "academic.html", sidebaricon: user-graduate}
  - {file: "README.md", sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Contact, icon: envelope, file: "contact.html"}
  - {title: Github, icon: github, url: "https://github.com/kksecops"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

collections: #define new collections
  academic:
    output: true
    permalink: /academic/:path/
  projects:
    output: true
    permalink: /projects/:path/
  writeups:
    output: true
    permalink: /writeups/:path/

plugins:
 - jekyll-feed
 - jekyll-paginate
